begin transaction;

drop schema if exists projet_IFT_2935 cascade;
create schema projet_IFT_2935;
set search_path to projet_IFT_2935;

create type facultes as enum
(
	'Arts et sciences',
	'Sciences de l éducation',
	'Droit',
	'Médecine',
	'Médecine dentaire',
	'Médecine vétérinaire',
	'Musique',
	'Optométrie',
	'Pharmacie',
	'Santé publique',
	'Sciences infirmières',
	'Éducation permanente',
	'Polytechnique',
	'HEC'
);

create type programmes as enum
(
	'ACCÈS - FEP',
	'Action communautaire',
	'Actuariat',
	'Administration de l éducation',
	'Administration de l éducation (D.Éd.)',
	'Administration des services de santé',
	'Administration des services de santé, Gestion des serv. inf.',
	'Administration des services de santé, administration sociale',
	'Administration des systèmes d éducation et de formation',
	'Administration des systèmes informatiques',
	'Administration sociale',
	'Affaires publiques et internationales',
	'Aménagement',
	'Aménagement, option Design Urbain',
	'Aménagement, option Design et complexité',
	'Aménagement, option Ville, territoire, paysage',
	'Aménagement, option conservation du patrimoine bâti',
	'Aménagement, option design, création et innovation',
	'Aménagement, option montage et gestion de projets aménagement',
	'Aménagement, option théories en design',
	'Analyse d affaires et technologies de l information (TI)',
	'Analyse des mégadonnées en santé',
	'Analyse des mégadonnées en sciences humaines et sociales',
	'Analyse et évaluation des interventions en santé',
	'Analyse et éval des services, organisations sys de santé',
	'Analyse et stratégie internationale',
	'Analyses environnementales et industrielles',
	'Andragogie',
	'Année préparatoire',
	'Année préparatoire - Musique',
	'Anthropologie',
	'Archéologie classique',
	'Architecture',
	'Architecture de paysage',
	'Archivistique',
	'Arts et lettres',
	'Arts et sciences',
	'Arts, création et technologies',
	'Audiologie',
	'Baccalauréat 120 crédits : année de transition',
	'Baccalauréat par cumul',
	'Baccalauréats 4 ans UdeM',
	'Baccalauréats par cumul en gestion',
	'Bio-informatique',
	'Biochimie',
	'Biochimie clinique',
	'Biochimie et médecine moléculaire',
	'Bioéthique',
	'Biologie (Sciences)',
	'Biologie moléculaire',
	'Biophysique et physiologie moléculaire',
	'Biostatistique',
	'Bureautique',
	'Chimie',
	'Cinéma',
	'Communication (Sciences)',
	'Communication appliquée',
	'Communication dans les organisations en changement',
	'Communication et Politique',
	'Communication médiatique',
	'Communication organisationnelle',
	'Communication politique',
	'Compétences professionnelles',
	'Compléments de formation',
	'Composition et arrangement jazz',
	'Conseil génétique',
	'Coopération et solidarité internationales',
	'Coopération internationale',
	'Créativité et innovation',
	'Créativité, innovation et entrepreneuriat',
	'Criminalistique et information',
	'Criminologie',
	'Criminologie - Analyse criminologique',
	'Criminologie - Campus Laval',
	'Criminologie - Intervention criminologique',
	'Cultures visuelles',
	'Cultures, sociétés et religions',
	'Démographie',
	'Démographie et Anthropologie',
	'Démographie et Géographie',
	'Démographie et Statistique',
	'Design : orientation design d intérieur',
	'Design : orientation design industriel',
	'Design d intérieur',
	'Design de jeux',
	'Design des jardins',
	'Design industriel',
	'Design urbain',
	'Développement du médicament',
	'Didactique',
	'Didactique et intégration des matières',
	'Direction et leadership',
	'Droit',
	'Droit - Fiscalité',
	'Droit - common law nord-américaine',
	'Droit des affaires',
	'Droit des technologies de l information',
	'Droit et travail',
	'Droit international',
	'Droit international - avec mémoire',
	'Droit international - avec travail dirigé',
	'Droit notarial',
	'Droit, option common law comparée',
	'Droit, option droit des affaires',
	'Droit, option droit des affaires - avec mémoire',
	'Droit, option droit des affaires contexte de globalisation',
	'Droit, option droit privé comparé',
	'Écodesign stratégique',
	'Économie (Sciences)',
	'Économie et Politique',
	'Écriture de scénario et création littéraire',
	'Édition numérique',
	'Éducation comparée et fondements de l éducation',
	'Éducation préscolaire et enseignement primaire - Campus Laval',
	'Éducation préscolaire et enseignement primaire - Campus MTL',
	'Éducation, option éducation préscolaire et ens primaire',
	'Éducation, option générale',
	'Éducation, option orthopédagogie',
	'Éducation, option pédagogie univ des sciences de la santé',
	'Enquête et renseignement',
	'Enseignement',
	'Enseignement au secondaire',
	'Enseignement éducation physique et à la santé',
	'Enseignement espagnol, langue seconde',
	'Enseignement éthique et de la cult religieuse au secondaire',
	'Enseignement histoire au collégial',
	'Enseignement univers social au secondaire',
	'Enseignement philosophie au collégial',
	'Enseignement des mathématiques au secondaire',
	'Enseignement des sciences et des technologies au secondaire',
	'Enseignement du français au secondaire',
	'Enseignement du français langue seconde',
	'Enseignement en adaptation scolaire - Campus Laval',
	'Enseignement en adaptation scolaire - Campus MTL',
	'Environnement et développement durable',
	'Environnement et développement durable (avec mémoire)',
	'Environnement et développement durable (avec stage)',
	'Environnement, santé et gestion des catastrophes',
	'Épidémiologie',
	'Épidémiologie et contrôle des infections',
	'Ergothérapie',
	'Éthique clinique',
	'Éthique clinique pédiatrique',
	'Éthique et droit',
	'Études allemandes',
	'Études allemandes dans le contexte européen',
	'Études allemandes et Histoire',
	'Études anglaises',
	'Études anglaises et Littérature comparée',
	'Études arabes',
	'Études asiatiques',
	'Études autochtones',
	'Études catalanes',
	'Études cinématographiques',
	'Études cinématographiques et Littérature comparée',
	'Études classiques',
	'Études classiques et Anthropologie',
	'Études du jeu vidéo',
	'Études du jeu vidéo (Cinéma)',
	'Études du phénomène criminel',
	'Études est-asiatiques',
	'Études européennes',
	'Études féministes, des genres et des sexualités',
	'Études hispaniques',
	'Études individualisées',
	'Études individualisées (ès arts)',
	'Études individualisées (ès sciences)',
	'Études individualisées - M.A.',
	'Études individualisées - M.Sc.',
	'Études individualisées - M.Sc.A.',
	'Études internationales',
	'Études italiennes',
	'Études juives',
	'Études latino-américaines',
	'Études libres - 1er cycle',
	'Études libres - 2e cycle',
	'Études libres - 3e cycle',
	'Études libres - hors Québec',
	'Études libres - langue seconde',
	'Études lusophones',
	'Études médiévales',
	'Études néo-helléniques',
	'Études québécoises',
	'Études religieuses',
	'Évaluation des compétences',
	'Évaluation des technologies de la santé',
	'Exploration de technologies informatiques',
	'Exploration en sciences humaines et sociales',
	'Finance',
	'Finance mathématique et computationnelle',
	'Fondements et pratiques en sciences sociales et santé',
	'Formation à l enseignement postsecondaire',
	'Formation préparatoire en relations industrielles',
	'français langue seconde: culture, études et travail',
	'Génétique médicale',
	'Génétique moléculaire',
	'Génie biomédical',
	'Génomique humaine',
	'Géographie',
	'Géographie appliquée en environnement',
	'Géographie environnementale',
	'Géographie et études environnementales',
	'Géomatique et analyse spatiale',
	'Géomatique et cartographie dynamique',
	'Gérontologie',
	'Gestion appliquée à la police et à la sécurité',
	'Gestion de l information numérique',
	'Gestion de la douleur chronique',
	'Gestion de la qualité de vie au travail',
	'Gestion de la qualité et de la sécurité des patients',
	'Gestion de projets',
	'Gestion des opérations et de la logistique',
	'Gestion des services de santé et des services sociaux',
	'Gestion du changement en éducation',
	'Gestion du changement et responsabilité populationnelle',
	'Gestion du système de santé',
	'Gestion en pharmacie d officine',
	'Gestion et sécurité des systèmes d information',
	'Gestion internationale',
	'Gestion philanthropique',
	'Gestion urbaine pour les pays en développement',
	'Histoire',
	'Histoire ancienne',
	'Histoire de l art',
	'Histoire et Études classiques',
	'Hygiène du travail',
	'Informatique',
	'Informatique appliquée',
	'Initiation à la programmation',
	'Initiation au multimédia',
	'Insertion professionnelle en enseignement',
	'Intégration pédagogique du numérique',
	'Internat de perf sciences appliquées vétérinaires',
	'Internat de perf sciences appliquées vét - disciplinaire',
	'Intervention auprès des jeunes : fondements et pratiques',
	'Intervention éducative',
	'Intervention en déficience intel. et troubles autisme',
	'Intervention en dépendances',
	'Intervention psychoéducative',
	'Intervention psychoéducative - Campus Laval',
	'Jazz et musiques du monde',
	'Jeu vidéo',
	'Journalisme',
	'Justice et victimes',
	'Kinésiologie',
	'Kinésiologie - Sciences de l activité physique',
	'Langue espagnole et cultures hispaniques',
	'Langue et culture allemandes',
	'Langue et culture anglaises',
	'Langue et culture arabes',
	'Langue et culture catalanes',
	'Langue et culture chinoises',
	'Langue et culture coréennes',
	'Langue et culture de la Grèce moderne',
	'Langue et culture grecques',
	'Langue et culture hispaniques',
	'Langue et culture innues',
	'Langue et culture italiennes',
	'Langue et culture japonaises',
	'Langue et culture latines',
	'Langue et culture néo-helléniques',
	'Langue et culture russes',
	'Langue portugaise et cultures lusophones',
	'Langues modernes',
	'Leadership appliqué à la santé',
	'Leadership et gestion des établissements scolaires',
	'Leadership pour militaires',
	'Lettres et sciences humaines',
	'Linguistique',
	'Linguistique et Psychologie',
	'Littérature',
	'Littérature comparée',
	'Littérature comparée et Philosophie',
	'Littératures de langue française',
	'Littératures de langue française et Linguistique',
	'Littératures de langue française et Philosophie',
	'Littératures de langues anglaise et française',
	'Marketing',
	'Mathématiques',
	'Mathématiques et Économie',
	'Mathématiques et Informatique',
	'Mathématiques et Physique',
	'Mathématiques et Statistique',
	'Médecine',
	'Médecine - Échocardiographie transœsophagienne périop',
	'Médecine cellulaire et moléculaire',
	'Médecine ass. et d expertise médicolégale (anglais)',
	'Médecine ass. et expertise en sciences de la santé',
	'Médecine ass. et expertise en sc de la santé - général',
	'Médecine ass. et expertise médicolégale intl (anglais)',
	'Médecine dentaire',
	'Médecine dentaire - Dentisterie pédiatrique',
	'Médecine dentaire - Orthodontie',
	'Médecine dentaire - Réhabilitation prosthodontique',
	'Médecine dentaire - Résidence multidisciplinaire',
	'Médecine dentaire - Sciences buccodentaires',
	'Médecine dentaire stomatologie - Résidence approfondie',
	'Médecine vétérinaire',
	'Médecine vétérinaire - Animaux de compagnie',
	'Médecine vétérinaire - Biomédecine vétérinaire',
	'Médecine vétérinaire - Diagnostic en laboratoire',
	'Médecine vétérinaire - Interface animal-homme-environnement',
	'Médecine vétérinaire - Internat de perf en sc appliquées',
	'Médecine vétérinaire - Interventions en santé publique',
	'Médecine vétérinaire - Pathologie vétérinaire',
	'Médecine vétérinaire - Sciences cliniques vétérinaires',
	'Médecine vétérinaire - Sciences vétérinaires',
	'Media, culture et technologie',
	'Médiation de la musique',
	'Mesure et évaluation en éducation',
	'Méthodologies d analyse sociologique',
	'Microbiologie environnementale',
	'Microbiologie et immunologie',
	'Mobilité, transport et urbanisme',
	'Montage et gestion de projets d aménagement',
	'Multimédia',
	'Muséologie',
	'Musique',
	'Musique - Arts',
	'Musique - Composition instrumentale',
	'Musique - Composition mixte',
	'Musique - Composition pour l écran et la scène',
	'Musique - Écriture',
	'Musique - Enseignement instrumental',
	'Musique - Interprétation',
	'Musique - Interprétation chant classique',
	'Musique - Interprétation instruments classiques',
	'Musique - Interprétation jazz',
	'Musique - Musicologie',
	'Musique - Répertoire d orchestre',
	'Musique - Répertoire d orchestre 2',
	'Musique, art et société',
	'Musique, option accompagnement au piano',
	'Musique, option composition et création sonore',
	'Musique, option composition pour l écran',
	'Musique, option direction d orchestre',
	'Musique, option interprétation',
	'Musique, option interprétation et composition jazz',
	'Musiques - Histoire - Sociétés',
	'Musiques numériques',
	'Neuropsychologie clinique',
	'Neuroscience cognitive',
	'Neurosciences',
	'Nutrition',
	'Optométrie',
	'Optométrie - Basse vision',
	'Optométrie - Informatique adaptée en déficience visuelle',
	'Optométrie - Interv. en déficience visuelle - mobilité',
	'Optométrie - Interv. en déficience visuelle - réadaptation',
	'Optométrie - Sciences de la vision',
	'Optométrie - intervention en déficience visuelle',
	'Orthodidactique des mathématiques',
	'Orthodidactique du français',
	'Orthopédagogie - Élèves en difficulté adapt/comportement',
	'Orthopédagogie - Élèves handicapés',
	'Orthopédagogie - Soutien à l apprentissage',
	'Orthophonie',
	'Pathologie et biologie cellulaire',
	'Pathologie moléculaire et médecine personnalisée',
	'Pédagogie universitaire des sciences de la santé',
	'Pédagogie universitaire des sciences médicales',
	'Perfusion extracorporelle',
	'Petite enfance et approche interprofessionnelle',
	'Petite enfance et famille',
	'Pharmacie',
	'Pharmacogénomique',
	'Pharmacologie',
	'Pharmacologie clinique',
	'Pharmacothérapie avancée',
	'Philosophie',
	'Philosophie et Études classiques',
	'Physiologie',
	'Physiologie moléculaire, cellulaire et intégrative',
	'Physiothérapie',
	'Physiothérapie - Rééducation périnéale et pelvienne',
	'Physiothérapie avancée en neuro-musculosquelettique',
	'Physique',
	'Physique et Informatique',
	'Physique médicale',
	'Planification financière personnelle',
	'Pratique avancée: expertise clinique',
	'Pratique avancée: expertise clinique intervention',
	'Pratique avancée: formation infirmière',
	'Pratique avancée: formation infirmière intervention',
	'Pratique avancée: gestion de proximité',
	'Pratique avancée: gestion proximité et intervention',
	'Pratique en pharmacie communautaire',
	'Pratique pharmaceutique',
	'Pratiques de la communication',
	'Pratiques et politiques du pluralisme',
	'Programmation',
	'Programmation Internet',
	'Programme d accueil en sciences',
	'Psychoéducation',
	'Psychoéducation - Campus Laval',
	'Psychologie',
	'Psychologie - Campus Laval',
	'Psychologie - Campus MTL',
	'Psychologie - option Neuropsychologie clinique',
	'Psychologie - option Psychologie clinique',
	'Psychologie - option psychologie du travail/organisations',
	'Psychologie - recherche et intervention',
	'Psychologie - rech et int - Neuropsychologie clinique',
	'Psychologie - rech et int - Psychologie clinique',
	'Psychologie - rech et int - Psychologie du travail et orgs',
	'Psychologie et Sociologie',
	'Psychopédagogie',
	'Publicité',
	'Publicité et communication créative',
	'Recherche interdisciplinaire en santé de la reproduction',
	'Recherche, développement et évaluation du médicament',
	'Récits et médias autochtones',
	'Rédaction',
	'Rédaction professionnelle',
	'Réglementation canadienne et québécoise de l immigration',
	'Relations ethniques',
	'Relations industrielles',
	'Relations industrielles - Dynamique des rel du travail',
	'Relations industrielles - Gestion diversité dans les orgs',
	'Relations industrielles - Gestion stratégique des RH',
	'Relations industrielles - Perspectives internationales',
	'Relations industrielles - Santé et mieux-être au travail',
	'Relations publiques',
	'Santé communautaire',
	'Santé environnementale et santé au travail',
	'Santé environnementale mondiale',
	'Santé et sécurité du travail',
	'Santé mentale',
	'Santé mentale : fondements et pratiques d intervention',
	'Santé mondiale',
	'Santé numérique',
	'Santé publique',
	'Santé publique environnementale et sécurité du travail',
	'Santé publique et mondialisation',
	'Santé publique pour cadres et professionnels en exercice',
	'Science politique',
	'Science politique et Philosophie',
	'Sciences biomédicales',
	'Sciences biopharmaceutiques',
	'Sciences cognitives',
	'Sciences de l éducation',
	'Sciences de l information (archives et bibliothéconomie)',
	'Sciences de l information - Recherche',
	'Sciences de l orthophonie et de l audiologie',
	'Sciences de la population',
	'Sciences de la réadaptation',
	'Sciences des données',
	'Sciences des religions',
	'Sciences humaines appliquées',
	'Sciences humaines et sociales',
	'Sciences infirmières',
	'Sciences infirmières (DEC-bac) - Campus Laval',
	'Sciences infirmières (DEC-bac) - Campus MTL',
	'Sciences infirmières - Dével. des pratiques infirmières',
	'Sciences infirmières - Évaluation santé et interventions',
	'Sciences infirmières - Formation initiale - Campus Laval',
	'Sciences infirmières - Formation initiale - Campus MTL',
	'Sciences infirmières - Leadership et gestion',
	'Sciences infirmières - Pratique avancée',
	'Sciences infirmières - Prév. et contrôle des infections',
	'Sciences infirmières - Soins palliatifs et de fin de vie',
	'Sciences infirmières : Pratique infirmière 1',
	'Sciences infirmières : Pratique infirmière 2',
	'Sciences infirmières : Profession et santé',
	'Sciences infirmières : Soins d urgence',
	'Sciences naturelles et formelles',
	'Sciences neurologiques',
	'Sciences pharmaceutiques',
	'Sciences pharmaceutiques, médicament et santé des populations',
	'Sciences religieuses',
	'Sécurité du travail et santé publique',
	'Sécurité et études policières',
	'Sécurité intérieure',
	'Service social',
	'Service social - Campus Laval',
	'Sexualité : enjeux de société et pratiques d intervention',
	'Société, politiques publiques et santé',
	'Sociologie',
	'Soins palliatifs et de fin de vie',
	'Soins pharmaceutiques',
	'Soins préhospitaliers d urgence avancés',
	'Soutien à la transition des élèves besoins particuliers',
	'Spiritualité et santé',
	'Statistique',
	'Statistiques sociales',
	'Synthèse et architectures moléculaires',
	'Technologie et innocuité des aliments',
	'Théologie',
	'Théologie - Études bibliques',
	'Théologie pratique',
	'Toxicologie et analyse du risque',
	'Toxicomanies : prévention et réadaptation',
	'Traduction',
	'Traduction 1',
	'Traduction 2',
	'Traduction troisième langue',
	'Travail social',
	'Travail social - Campus Laval',
	'Travail social - Campus MTL',
	'Urbanisme',
	'Victimologie',
	'Virologie et immunologie'
);

create type disciplines as enum
(
	'École de travail social',
	'Mathématiques et statistique',
	'Admin. et fondements de l éduc',
	'Gestion / éval./ pol. de santé',
	'Faculté des sc. infirmières,Gestion / éval./ pol. de santé',
	'Faculté des arts et des sc,Gestion / éval./ pol. de santé',
	'Informatique et rech. opér.',
	'Science politique',
	'Design',
	'Urbanisme/architecture paysage',
	'Faculté des arts et des sciences,Direction (Santé publique)',
	'Direction Arts et sciences',
	'Administration de la santé',
	'Chimie',
	'Psychopédagogie et andragogie',
	'SAFIRE',
	'Anthropologie',
	'Centre d études classiques',
	'Architecture',
	'Architecture de paysage',
	'Bibliothéconomie',
	'Orthophonie et audiologie',
	'Biochimie/médecine moléculaire',
	'Biochimie',
	'Médecine sociale et préventive',
	'Sciences biologiques',
	'Physique',
	'Faculté des arts et des sciences',
	'Histoire de l art',
	'Communication',
	'Criminologie',
	'Démographie',
	'Démographie,Anthropologie',
	'Démographie,Géographie',
	'Démographie,Mathématiques et statistique',
	'Didactique',
	'Relations industrielles',
	'Direction Polytechnique',
	'Sciences économiques',
	'Science politique,Sciences économiques',
	'Histoire de l art,Littératures lang. française',
	'Formation initiale des maîtres',
	'Faculté de médecine',
	'Littératures et lang. modernes',
	'Histoire',
	'Philosophie',
	'Faculté de l aménagement',
	'Santé env. et santé au travail',
	'Réadaptation',
	'Pédiatrie',
	'Littératures/langues du monde',
	'Littératures et lang. modernes,Histoire',
	'Études anglaises,Littérature comparée',
	'Études Asie de l est',
	'Histoire de l art,Littérature comparée',
	'Centre d études classiques,Anthropologie',
	'Littérature comparée',
	'Faculté des arts et des sciences,Faculté de l aménagement',
	'Faculté de médecine,Études supérieures et postdoctorales',
	'Études supérieures et postdoctorales',
	'Ét. classiques et médiévales',
	'Littératures lang. française',
	'Institut d études religieuses',
	'Mathématiques et statistique,Sciences économiques',
	'Faculté des arts et des sc,Faculté éducation permanente',
	'Pharmacologie et physiologie',
	'Géographie',
	'Urbanisme',
	'Centre d études classiques,Histoire',
	'Sciences cliniques',
	'Faculté de droit,Faculté de l éducation permanente',
	'Kinésiologie / sc.act.physique',
	'Faculté de l éducation permanente',
	'Linguistique et traduction',
	'Linguistique et traduction,Psychologie',
	'Littérature comparée,Philosophie',
	'Littératures lang. française,Linguistique et traduction',
	'Littératures lang. française,Philosophie',
	'Sciences économiques,Mathématiques et statistique',
	'Informatique et rech. opér.,Mathématiques et statistique',
	'Mathématiques et statistique,Physique',
	'Anesthésio./méd. de la douleur',
	'Santé buccale',
	'Dentisterie de restauration',
	'Biomédecine vétérinaire',
	'Pathologie et microbiologie',
	'Sociologie',
	'Microbio. infectio. et immuno.',
	'Psychologie',
	'Neurosciences',
	'Nutrition',
	'Direction Optométrie',
	'Faculté de médecine,Ophtalmologie',
	'Pathologie et biologie cellul.',
	'Chirurgie',
	'Direction Pharmacie',
	'Philosophie,Centre d études classiques',
	'Physiologie',
	'Physique,Informatique et rech. opér.',
	'Psychoéducation',
	'Sociologie,Psychologie',
	'Faculté de médecine,Faculté des sciences infirmières',
	'Psychiatrie et addictologie',
	'École de santé publique,Faculté des sciences infirmières',
	'Direction (Santé publique)',
	'École de santé publique',
	'Médecine sociale,Gestion/éval./pol.santé,Santé env./travail',
	'Programmes de cycles supérieurs en sciences biomédicales',
	'Faculté des sciences infirmières',
	'Médecine de famille/d urgence'
);

commit;